Repository ant-design/x, pull requests merged in 2025-05, with the labels that each got.

#810 chore: sync main to feature branch
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README-zh_CN.md
  README.md
  components/attachments/style/fileCard.ts
  components/bubble/__tests__/__snapshots__/demo.test.ts.snap
  components/bubble/demo/list.tsx
  components/bubble/demo/markdown.tsx
  components/conversations/Item.tsx
  components/conversations/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/conversations/__tests__/__snapshots__/demo.test.ts.snap
  components/conversations/__tests__/__snapshots__/index.test.tsx.snap
  components/conversations/style/index.ts
  components/index.ts
  components/prompts/style/index.ts
  components/suggestion/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/thought-chain/__tests__/index.test.tsx
  components/thought-chain/demo/collapsible.tsx
  components/use-x-agent/index.en-US.md
  components/use-x-agent/index.ts
  components/use-x-agent/index.zh-CN.md
  components/use-x-chat/index.ts
  docs/playground/copilot.tsx
  docs/playground/independent.tsx
  package.json
Labels: documentation, BranchAutoMerge, lgtm

#827 chore: fix warning of deprecated API
  components/suggestion/index.tsx
  package.json
Labels: bug, lgtm

#229 chore: delete webpack.config.js
  .dumirc.ts
  .fatherrc.ts
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
  package.json
  webpack.config.js
Labels: documentation, enhancement, lgtm

#814 docs(bubble): update content and messageRender type
  components/bubble/index.en-US.md
  components/bubble/index.zh-CN.md
Labels: documentation, lgtm

#835 docs: sender supplement documents to address user inquiries
  components/sender/index.en-US.md
  components/sender/index.zh-CN.md
Labels: documentation, lgtm

#842 chore: sync main to feature branch
  .dumirc.ts
  .fatherrc.ts
  components/bubble/index.en-US.md
  components/bubble/index.zh-CN.md
  components/suggestion/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/suggestion/index.tsx
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
  package.json
  webpack.config.js
Labels: documentation, BranchAutoMerge

#683 feat: make the Bubble foot and header to get from context & Bubble can get key
  CHANGELOG.en-US.md
  components/bubble/Bubble.tsx
  components/bubble/BubbleList.tsx
  components/bubble/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/bubble/__tests__/__snapshots__/demo.test.ts.snap
  components/bubble/demo/custom-content.md
  components/bubble/demo/custom-content.tsx
  components/bubble/demo/debug.tsx
  components/bubble/demo/header-and-footer.tsx
  components/bubble/demo/list-custom.tsx
  components/bubble/demo/semantic-list-custom.md
  components/bubble/demo/semantic-list-custom.tsx
  components/bubble/hooks/useTypedEffect.ts
  components/bubble/index.en-US.md
  components/bubble/index.zh-CN.md
  components/bubble/interface.ts
  components/prompts/style/index.ts
  components/thought-chain/demo/collapsible.tsx
  components/use-x-agent/index.en-US.md
  components/use-x-agent/index.zh-CN.md
  components/use-x-chat/index.ts
  docs/playground/copilot.tsx
  docs/playground/independent.tsx
Labels: lgtm

#840 fix: resolve the security issues of apikey
  components/use-x-agent/demo/model.tsx
  components/use-x-chat/demo/model.tsx
  components/x-request/demo/model.tsx
  components/x-request/index.ts
  docs/playground/copilot.tsx
  docs/playground/independent.tsx
Labels: bug, documentation, lgtm

#845 docs: changelog of 1.3.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: documentation, lgtm

#846 chore: sync main to next branch
  .dumirc.ts
  .fatherrc.ts
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/bubble/Bubble.tsx
  components/bubble/BubbleList.tsx
  components/bubble/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/bubble/__tests__/__snapshots__/demo.test.ts.snap
  components/bubble/demo/custom-content.md
  components/bubble/demo/custom-content.tsx
  components/bubble/demo/debug.tsx
  components/bubble/demo/header-and-footer.tsx
  components/bubble/demo/list-custom.tsx
  components/bubble/demo/semantic-list-custom.md
  components/bubble/demo/semantic-list-custom.tsx
  components/bubble/hooks/useTypedEffect.ts
  components/bubble/index.en-US.md
  components/bubble/index.zh-CN.md
  components/bubble/interface.ts
  components/prompts/style/index.ts
  components/sender/index.en-US.md
  components/sender/index.zh-CN.md
  components/suggestion/index.tsx
  components/thought-chain/demo/collapsible.tsx
  components/use-x-agent/demo/model.tsx
  components/use-x-agent/index.en-US.md
  components/use-x-agent/index.zh-CN.md
  components/use-x-chat/demo/model.tsx
  components/use-x-chat/index.ts
  components/x-request/demo/model.tsx
  components/x-request/index.ts
  docs/playground/copilot.tsx
  docs/playground/independent.tsx
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
  package.json
  webpack.config.js
Labels: BranchAutoMerge

#816 feat: demo在消息请求过程中不可创建会话
  docs/playground/copilot.tsx
  docs/playground/independent.tsx
Labels: lgtm

#768 feat: New Actions
  components/actions/ActionMenu.tsx
  components/actions/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/actions/__tests__/__snapshots__/demo.test.ts.snap
  components/actions/__tests__/demo-extend.test.ts
  components/actions/__tests__/demo.test.ts
  components/actions/__tests__/image.test.ts
  components/actions/__tests__/index.test.tsx
  components/actions/demo/basic.md
  components/actions/demo/basic.tsx
  components/actions/demo/sub.md
  components/actions/demo/sub.tsx
  components/actions/demo/variant.md
  components/actions/demo/variant.tsx
  components/actions/index.en-US.md
  components/actions/index.tsx
  components/actions/index.zh-CN.md
  components/actions/interface.ts
  components/actions/style/index.ts
  components/index.ts
  components/theme/components.ts
  components/x-provider/context.ts
  components/x-provider/index.en-US.md
  components/x-provider/index.zh-CN.md
  tests/__snapshots__/index.test.ts.snap
Labels: lgtm

#877 fix: Conversations ellipsis lose efficacy
  components/conversations/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/conversations/__tests__/__snapshots__/demo.test.ts.snap
  components/conversations/demo/basic.tsx
  components/conversations/demo/group.tsx
  components/conversations/style/index.ts
Labels: bug, lgtm

#882 docs: changelog of 1.4.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: documentation, lgtm

#883 chore: sync main to next branch
  packages/x/CHANGELOG.en-US.md
  packages/x/CHANGELOG.zh-CN.md
  packages/x/components/actions/ActionMenu.tsx
  packages/x/components/actions/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/actions/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/actions/__tests__/demo-extend.test.ts
  packages/x/components/actions/__tests__/demo.test.ts
  packages/x/components/actions/__tests__/image.test.ts
  packages/x/components/actions/__tests__/index.test.tsx
  packages/x/components/actions/demo/basic.md
  packages/x/components/actions/demo/basic.tsx
  packages/x/components/actions/demo/sub.md
  packages/x/components/actions/demo/sub.tsx
  packages/x/components/actions/demo/variant.md
  packages/x/components/actions/demo/variant.tsx
  packages/x/components/actions/index.en-US.md
  packages/x/components/actions/index.tsx
  packages/x/components/actions/index.zh-CN.md
  packages/x/components/actions/interface.ts
  packages/x/components/actions/style/index.ts
  packages/x/components/bubble/BubbleList.tsx
  packages/x/components/bubble/demo/markdown.tsx
  packages/x/components/conversations/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/conversations/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/conversations/demo/basic.tsx
  packages/x/components/conversations/demo/group.tsx
  packages/x/components/conversations/style/index.ts
  packages/x/components/index.ts
  packages/x/components/theme/components.ts
  packages/x/components/use-x-agent/demo/model.tsx
  packages/x/components/use-x-chat/demo/model.tsx
  packages/x/components/x-provider/context.ts
  packages/x/components/x-provider/index.en-US.md
  packages/x/components/x-provider/index.zh-CN.md
  packages/x/components/x-request/demo/model.tsx
  packages/x/docs/playground/copilot.tsx
  packages/x/docs/playground/independent.tsx
  packages/x/package.json
  packages/x/tests/__snapshots__/index.test.ts.snap
Labels: javascript, BranchAutoMerge
