Repository ant-design/x, pull requests merged in 2025-09, with the labels that each got.

#1156 fix: file-card status fix
  packages/x/components/attachments/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/file-card/List.tsx
Labels: bug, lgtm

#1160 fix: bubble import type
  packages/x/.dumi/pages/index/components/SceneIntroduction/Assistant.tsx
  packages/x/.dumi/pages/index/components/SceneIntroduction/Independent.tsx
  packages/x/components/bubble/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/bubble/demo/list-ref.tsx
  packages/x/components/bubble/demo/list.tsx
  packages/x/components/bubble/demo/markdown.tsx
  packages/x/components/index.ts
  packages/x/docs/x-markdown/demo/codeDemo/components.tsx
  packages/x/docs/x-markdown/demo/codeDemo/streaming.tsx
  packages/x/docs/x-markdown/demo/components/dataChart.tsx
  packages/x/docs/x-markdown/demo/components/think.tsx
  packages/x/docs/x-markdown/demo/streaming/animation.tsx
  packages/x/docs/x-markdown/demo/streaming/format.tsx
  packages/x/docs/x-markdown/demo/supersets/HighlightCode/basic.tsx
  packages/x/docs/x-markdown/demo/supersets/HighlightCode/streaming.tsx
  packages/x/docs/x-markdown/demo/supersets/Latex/basic.tsx
  packages/x/docs/x-markdown/demo/supersets/Latex/streaming.tsx
  packages/x/docs/x-markdown/demo/supersets/Mermaid/basic.tsx
  packages/x/docs/x-markdown/demo/supersets/Mermaid/streaming.tsx
  packages/x/docs/x-sdk/demos/x-chat/basic.tsx
  packages/x/docs/x-sdk/demos/x-chat/model.tsx
Labels: bug, lgtm

#1169 feat: add updating status and update docs
  packages/x-sdk/src/x-chat/index.ts
  packages/x/docs/playground/agent-tbox.tsx
  packages/x/docs/playground/copilot.tsx
  packages/x/docs/playground/independent.tsx
  packages/x/docs/x-sdk/chat-provider.en-US.md
  packages/x/docs/x-sdk/chat-provider.zh-CN.md
Labels: documentation, enhancement, lgtm

#1182 fix: markdown theme & Unified Type Naming
  packages/x-markdown/src/XMarkdown/index.less
  packages/x-markdown/src/themes/dark.css
  packages/x-markdown/src/themes/light.css
  packages/x/.dumi/pages/index/components/SceneIntroduction/Assistant.tsx
  packages/x/.dumi/pages/index/components/SceneIntroduction/Independent.tsx
  packages/x/.dumi/pages/index/components/SceneIntroduction/Portal/Agent.tsx
  packages/x/components/bubble/BubbleList.tsx
  packages/x/components/bubble/__tests__/list.test.tsx
  packages/x/components/bubble/demo/list-ref.tsx
  packages/x/components/bubble/demo/list.tsx
  packages/x/components/bubble/index.en-US.md
  packages/x/components/bubble/index.tsx
  packages/x/components/bubble/index.zh-CN.md
  packages/x/components/bubble/interface.ts
  packages/x/components/index.ts
  packages/x/components/prompts/__tests__/index.test.tsx
  packages/x/components/prompts/index.tsx
  packages/x/components/thought-chain/Node.tsx
  packages/x/components/thought-chain/__tests__/index.test.tsx
  packages/x/components/thought-chain/demo/_semantic.tsx
  packages/x/components/thought-chain/demo/customization.md
  packages/x/components/thought-chain/demo/customization.tsx
  packages/x/components/thought-chain/demo/status.tsx
  packages/x/components/thought-chain/index.en-US.md
  packages/x/components/thought-chain/index.tsx
  packages/x/components/thought-chain/index.zh-CN.md
  packages/x/components/thought-chain/interface.ts
  packages/x/docs/x-markdown/demo/components/thoughtChain.tsx
  packages/x/docs/x-sdk/demos/x-request/basic.tsx
  packages/x/docs/x-sdk/demos/x-request/custom-params.tsx
  packages/x/docs/x-sdk/demos/x-request/custom-transformer.tsx
  packages/x/docs/x-sdk/demos/x-request/model.tsx
  packages/x/docs/x-sdk/demos/x-request/timeout.tsx
Labels: bug, documentation, lgtm

#1175 Fix(XMarkdown)：Mermaid 切换时渲染异常
  packages/x-markdown/src/XMarkdown/index.tsx
  packages/x-markdown/src/plugins/Mermaid/index.tsx
  packages/x/docs/x-markdown/demo/supersets/CustomPlugin/custom.tsx
Labels: bug

#1186 chore: update site config
  README-zh_CN.md
  README.md
  packages/x/.dumi/theme/layouts/DocLayout/index.tsx
  packages/x/docs/react/introduce.en-US.md
  packages/x/docs/react/introduce.zh-CN.md
  packages/x/scripts/previewEditor/template.html
Labels: documentation, lgtm

#1191 chore: update tbox website
  docs/react/agent-use-tbox.en-US.md
  docs/react/agent-use-tbox.zh-CN.md
Labels: documentation, lgtm

#1193 chore: update og:image
  packages/x/.dumi/theme/common/CommonHelmet.tsx
  packages/x/.dumi/theme/layouts/DocLayout/index.tsx
  packages/x/.dumi/theme/layouts/IndexLayout/index.tsx
  packages/x/scripts/previewEditor/template.html
Labels: documentation, lgtm

#1194 fix: update playground & fix Actions Semantic & update OpenAI model
  packages/x/components/actions/ActionsFeedback.tsx
  packages/x/components/actions/Item.tsx
  packages/x/components/actions/demo/preset.tsx
  packages/x/components/actions/interface.ts
  packages/x/components/bubble/Bubble.tsx
  packages/x/components/bubble/BubbleList.tsx
  packages/x/components/bubble/context.ts
  packages/x/components/bubble/interface.ts
  packages/x/docs/playground/agent-tbox.tsx
  packages/x/docs/playground/independent.tsx
  packages/x/docs/react/demo/tbox.tsx
  packages/x/docs/x-sdk/demos/x-chat/model.tsx
Labels: documentation, lgtm

#1198 Feature(XMarkdown)：动画调整 & 导出类型修改
  packages/x-markdown/package.json
  packages/x-markdown/src/XMarkdown/AnimationNode.tsx
  packages/x-markdown/src/XMarkdown/__test__/AnimationNode.test.tsx
  packages/x-markdown/src/XMarkdown/__test__/hooks.test.tsx
  packages/x-markdown/src/XMarkdown/core/Renderer.ts
  packages/x-markdown/src/XMarkdown/interface.ts
  packages/x-markdown/src/index.ts
  packages/x-markdown/src/plugins/HighlightCode/__test__/index.test.tsx
  packages/x/docs/playground/agent-tbox.tsx
  packages/x/docs/playground/copilot.tsx
  packages/x/docs/playground/independent.tsx
  packages/x/docs/x-markdown/demo/_utils/index.tsx
  packages/x/docs/x-markdown/demo/codeDemo/plugin.tsx
  packages/x/docs/x-markdown/demo/codeDemo/supersets.tsx
  packages/x/docs/x-markdown/demo/components/compare.tsx
  packages/x/docs/x-markdown/demo/components/custom.tsx
  packages/x/docs/x-markdown/demo/components/think.tsx
  packages/x/docs/x-markdown/demo/components/thoughtChain.tsx
  packages/x/docs/x-markdown/demo/streaming/animation.tsx
  packages/x/docs/x-markdown/demo/supersets/CustomPlugin/custom.tsx
  packages/x/docs/x-markdown/demo/supersets/HighlightCode/basic.tsx
  packages/x/docs/x-markdown/demo/supersets/HighlightCode/streaming.tsx
  packages/x/docs/x-markdown/demo/supersets/Mermaid/basic.tsx
  packages/x/docs/x-markdown/demo/supersets/Mermaid/streaming.tsx
  packages/x/docs/x-markdown/demo/xprovider/locale.tsx
  packages/x/docs/x-markdown/demo/xprovider/theme.tsx
  packages/x/docs/x-markdown/examples.en-US.md
  packages/x/docs/x-markdown/examples.zh-CN.md
  packages/x/docs/x-markdown/streaming.en-US.md
  packages/x/docs/x-markdown/streaming.zh-CN.md
  packages/x/docs/x-sdk/demos/x-chat/deepSeek.tsx
Labels: documentation, 2.x, lgtm

#1199 Docs(XMarkdown): Component Docs
  packages/x/docs/x-markdown/components-custom.en-US.md
  packages/x/docs/x-markdown/components-custom.zh-CN.md
  packages/x/docs/x-markdown/components-data.en-US.md
  packages/x/docs/x-markdown/components-data.zh-CN.md
  packages/x/docs/x-markdown/components-think.en-US.md
  packages/x/docs/x-markdown/components-think.zh-CN.md
  packages/x/docs/x-markdown/components.en-US.md
  packages/x/docs/x-markdown/components.zh-CN.md
  packages/x/docs/x-markdown/examples.en-US.md
  packages/x/docs/x-markdown/examples.zh-CN.md
Labels: documentation, lgtm

#1197 chore(ci): use setup-utoo
  .github/workflows/main.yml
  .github/workflows/preview-build.yml
  .github/workflows/site-deploy.yml
  packages/x/package.json
Labels: 2.x, lgtm

#1205 docs: update icon
  packages/x/docs/x-markdown/demo/streaming/format.tsx
Labels: documentation, lgtm

#1204 Feature(XMarkdown):Animation
  packages/x-markdown/src/XMarkdown/AnimationNode.tsx
  packages/x-markdown/src/XMarkdown/__test__/AnimationNode.test.tsx
  packages/x-markdown/src/XMarkdown/hooks/useAnimation.tsx
  packages/x-markdown/src/XMarkdown/index.less
  packages/x-markdown/src/XMarkdown/interface.ts
  packages/x/docs/x-markdown/examples.en-US.md
  packages/x/docs/x-markdown/streaming.zh-CN.md
Labels: documentation, enhancement, 2.x, lgtm

#1214 chore: changelog of 2.0.0-alpha.9
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
  packages/x-markdown/package.json
  packages/x-sdk/package.json
  packages/x/package.json
Labels: documentation, lgtm

#1210 chore: merge next-alpha to next
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: documentation, BranchAutoMerge, lgtm

#1110 透传CascaderProps其他参数
  components/suggestion/index.tsx
Labels: javascript, lgtm

#1216 docs: update the XProvider theme demo
  packages/x-markdown/package.json
  packages/x/components/x-provider/demo/theme.tsx
  packages/x/docs/playground/ultramodern.tsx
  packages/x/package.json
Labels: documentation, lgtm

#1217 chore(XMarkdown): docs path and word space
  packages/x-markdown/README-zh_CN.md
  packages/x-markdown/package.json
  packages/x-sdk/package.json
  packages/x/.dumi/theme/builtins/MarkdownPluginsOverView.tsx
  packages/x/.dumi/theme/common/EditButton.tsx
  packages/x/.dumi/theme/slots/Header/Navigation.tsx
  packages/x/.dumirc.ts
  packages/x/components/bubble/index.en-US.md
  packages/x/components/bubble/index.zh-CN.md
  packages/x/components/introduce/index.en-US.md
  packages/x/components/introduce/index.zh-CN.md
  packages/x/docs/react/agent-use-tbox.en-US.md
  packages/x/docs/react/agent-use-tbox.zh-CN.md
  packages/x/docs/react/introduce.en-US.md
  packages/x/docs/react/introduce.zh-CN.md
  packages/x/docs/react/model-use-qwen.en-US.md
  packages/x/docs/react/model-use-qwen.zh-CN.md
  packages/x/docs/x-markdown/demo/_utils/adx-markdown.ts
  packages/x/docs/x-markdown/examples.en-US.md
  packages/x/docs/x-markdown/examples.zh-CN.md
  packages/x/docs/x-markdown/introduce.en-US.md
  packages/x/docs/x-markdown/introduce.zh-CN.md
  packages/x/docs/x-markdown/plugins.en-US.md
  packages/x/docs/x-markdown/plugins.zh-CN.md
  packages/x/docs/x-markdown/streaming.zh-CN.md
  packages/x/docs/x-markdown/themes.zh-CN.md
  packages/x/docs/x-sdk/use-x-chat.en-US.md
  packages/x/docs/x-sdk/use-x-chat.zh-CN.md
Labels: documentation, lgtm

#1224 docs: SeeConf link
  .dumi/pages/index/components/MainBanner.tsx
Labels: documentation, lgtm
