Repository ant-design/x, pull requests merged in 2025-08, with the labels that each got.

#1089 docs(bubble2.0): XMarkdown
  packages/x/components/bubble/demo/gpt-vis.tsx
Labels: documentation, lgtm

#1082 feat: x-sdk init
  packages/x-sdk/.jest.js
  packages/x-sdk/package.json
  packages/x-sdk/src/__test__/index.test.ts
  packages/x-sdk/src/_util/type.ts
  packages/x-sdk/src/index.ts
  packages/x-sdk/src/x-chat/index.ts
  packages/x-sdk/src/x-chat/providers/AbstractChatProvider.ts
  packages/x-sdk/src/x-chat/providers/DefaultChatProvider.ts
  packages/x-sdk/src/x-chat/providers/OpenAIChatProvider.ts
  packages/x-sdk/src/x-chat/providers/index.ts
  packages/x-sdk/src/x-chat/useSyncState.ts
  packages/x-sdk/src/x-conversations/__test__/index.test.tsx
  packages/x-sdk/src/x-conversations/index.ts
  packages/x-sdk/src/x-conversations/store.ts
  packages/x-sdk/src/x-mcp-client/__test__/index.test.ts
  packages/x-sdk/src/x-mcp-client/index.ts
  packages/x-sdk/src/x-model/__test__/index.test.ts
  packages/x-sdk/src/x-model/index.ts
  packages/x-sdk/src/x-request/__test__/abort.test.ts
  packages/x-sdk/src/x-request/__test__/index.test.ts
  packages/x-sdk/src/x-request/__test__/x-fetch.test.tsx
  packages/x-sdk/src/x-request/index.ts
  packages/x-sdk/src/x-request/x-fetch.ts
  packages/x-sdk/src/x-stream/__test__/index.test.ts
  packages/x-sdk/src/x-stream/index.ts
  packages/x-sdk/tests/index.test.ts
  packages/x-sdk/tests/setup-streams.ts
  packages/x-sdk/tests/setup.ts
  packages/x-sdk/tests/utils.tsx
  packages/x/.dumi/rehypeAntd.ts
  packages/x/docs/x-sdk/demos/x-chat/basic.md
  packages/x/docs/x-sdk/demos/x-chat/basic.tsx
  packages/x/docs/x-sdk/demos/x-chat/model.md
  packages/x/docs/x-sdk/demos/x-chat/model.tsx
  packages/x/docs/x-sdk/demos/x-conversations/basic.tsx
  packages/x/docs/x-sdk/demos/x-conversations/multi-instances.tsx
  packages/x/docs/x-sdk/demos/x-conversations/operations.tsx
  packages/x/docs/x-sdk/demos/x-request/basic.md
  packages/x/docs/x-sdk/demos/x-request/basic.tsx
  packages/x/docs/x-sdk/demos/x-request/custom-params.md
  packages/x/docs/x-sdk/demos/x-request/custom-params.tsx
  packages/x/docs/x-sdk/demos/x-request/custom-transformer.md
  packages/x/docs/x-sdk/demos/x-request/custom-transformer.tsx
  packages/x/docs/x-sdk/demos/x-request/model.md
  packages/x/docs/x-sdk/demos/x-request/model.tsx
  packages/x/docs/x-sdk/demos/x-request/timeout.md
  packages/x/docs/x-sdk/demos/x-request/timeout.tsx
  packages/x/docs/x-sdk/introduce.zh-CN.md
  packages/x/docs/x-sdk/use-x-chat.zh-CN.md
  packages/x/docs/x-sdk/use-x-conversations.zh-CN.md
  packages/x/docs/x-sdk/x-request.zh-CN.md
  packages/x/docs/x-sdk/x-stream.zh-CN.md
  packages/x/package.json
Labels: enhancement

#1094 feat: add file-card component
  packages/x/components/attachments/FileList/AudioIcon.tsx
  packages/x/components/attachments/FileList/FileListCard.tsx
  packages/x/components/attachments/FileList/VideoIcon.tsx
  packages/x/components/attachments/FileList/index.tsx
  packages/x/components/attachments/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/attachments/__tests__/__snapshots__/demo.test.tsx.snap
  packages/x/components/attachments/__tests__/__snapshots__/index.test.tsx.snap
  packages/x/components/attachments/__tests__/file-list.test.tsx
  packages/x/components/attachments/__tests__/index.test.tsx
  packages/x/components/attachments/demo/files-custom.md
  packages/x/components/attachments/demo/files-custom.tsx
  packages/x/components/attachments/demo/files.md
  packages/x/components/attachments/demo/files.tsx
  packages/x/components/attachments/index.en-US.md
  packages/x/components/attachments/index.tsx
  packages/x/components/attachments/index.zh-CN.md
  packages/x/components/attachments/style/fileCard.ts
  packages/x/components/attachments/style/index.ts
  packages/x/components/file-card/FileCard.tsx
  packages/x/components/file-card/List.tsx
  packages/x/components/file-card/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/file-card/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/file-card/__tests__/__snapshots__/index.test.tsx.snap
  packages/x/components/file-card/__tests__/demo-extend.test.ts
  packages/x/components/file-card/__tests__/demo.test.ts
  packages/x/components/file-card/__tests__/image.test.ts
  packages/x/components/file-card/__tests__/index.test.tsx
  packages/x/components/file-card/components/File.tsx
  packages/x/components/file-card/demo/_semantic.tsx
  packages/x/components/file-card/demo/audio.md
  packages/x/components/file-card/demo/audio.tsx
  packages/x/components/file-card/demo/basic.md
  packages/x/components/file-card/demo/basic.tsx
  packages/x/components/file-card/demo/icon.md
  packages/x/components/file-card/demo/icon.tsx
  packages/x/components/file-card/demo/image.md
  packages/x/components/file-card/demo/image.tsx
  packages/x/components/file-card/demo/list.md
  packages/x/components/file-card/demo/list.tsx
  packages/x/components/file-card/demo/mask.md
  packages/x/components/file-card/demo/mask.tsx
  packages/x/components/file-card/demo/overflow.md
  packages/x/components/file-card/demo/overflow.tsx
  packages/x/components/file-card/demo/size.md
  packages/x/components/file-card/demo/size.tsx
  packages/x/components/file-card/icons/audio.tsx
  packages/x/components/file-card/icons/video.tsx
  packages/x/components/file-card/index.en-US.md
  packages/x/components/file-card/index.tsx
  packages/x/components/file-card/index.zh-CN.md
  packages/x/components/file-card/style/index.ts
  packages/x/components/file-card/utils.ts
  packages/x/components/index.ts
  packages/x/components/sender/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/sender/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/theme/interface/components.ts
  packages/x/components/think/Think.tsx
  packages/x/components/x-provider/context.ts
  packages/x/tests/__snapshots__/index.test.ts.snap
Labels: enhancement, 2.x, lgtm

#1100 feat: editable bubble
  packages/x/components/bubble/Bubble.tsx
  packages/x/components/bubble/EditableContent.tsx
  packages/x/components/bubble/TypingContent.tsx
  packages/x/components/bubble/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/bubble/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/bubble/__tests__/index.test.tsx
  packages/x/components/bubble/demo/editable.md
  packages/x/components/bubble/demo/editable.tsx
  packages/x/components/bubble/demo/list.tsx
  packages/x/components/bubble/index.en-US.md
  packages/x/components/bubble/index.zh-CN.md
  packages/x/components/bubble/interface.ts
  packages/x/components/bubble/style/bubble.ts
  packages/x/components/bubble/style/content.ts
  packages/x/components/locale/en_US.ts
  packages/x/components/locale/index.tsx
  packages/x/components/locale/zh_CN.ts
Labels: enhancement, javascript, lgtm

#824 fix: 修复useActive 中 items 为空数组导致的异常
  components/suggestion/__tests__/useActive.test.tsx
  components/suggestion/useActive.ts
Labels: bug, lgtm

#1091 fix: Simplify the logic for using common prefixes in typing hooks.
  components/bubble/hooks/useTypedEffect.ts
Labels: bug, lgtm

#1122 chore: enable utoopack when bundle umd
  .fatherrc.ts
  .jest.js
  .npmrc
  package.json
Labels: lgtm

#1133 docs(Bubble): Bubble.List autoScroll explanation
  packages/x/components/bubble/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/bubble/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/bubble/demo/list.tsx
  packages/x/components/bubble/index.en-US.md
  packages/x/components/bubble/index.zh-CN.md
Labels: documentation

#1130 fix: File card SemanticType
  packages/x/components/attachments/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/file-card/FileCard.tsx
  packages/x/components/file-card/List.tsx
  packages/x/components/file-card/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/file-card/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/file-card/components/File.tsx
  packages/x/components/file-card/demo/_semantic-list.tsx
  packages/x/components/file-card/demo/audio.tsx
  packages/x/components/file-card/demo/basic.tsx
  packages/x/components/file-card/demo/image.tsx
  packages/x/components/file-card/demo/list.tsx
  packages/x/components/file-card/index.en-US.md
  packages/x/components/file-card/index.zh-CN.md
  packages/x/components/file-card/style/index.ts
  packages/x/components/thought-chain/Item.tsx
  packages/x/components/thought-chain/demo/_semantic-item.tsx
  packages/x/components/thought-chain/index.tsx
  packages/x/components/thought-chain/index.zh-CN.md
Labels: bug, lgtm

#1140 fix: attachments upload show image
  packages/x/components/attachments/FileList/index.tsx
Labels: bug, lgtm

#1139 feat: refactor playground
  biome.json
  packages/x-sdk/.fatherrc.ts
  packages/x-sdk/src/index.ts
  packages/x-sdk/src/x-chat/__test__/providers.test.ts
  packages/x-sdk/src/x-chat/index.ts
  packages/x-sdk/src/x-chat/providers/AbstractChatProvider.ts
  packages/x-sdk/src/x-chat/providers/index.ts
  packages/x-sdk/src/x-conversations/index.ts
  packages/x-sdk/src/x-conversations/store.ts
  packages/x-sdk/src/x-request/index.ts
  packages/x/.dumi/theme/plugin.ts
  packages/x/components/actions/ActionsAudio.tsx
  packages/x/components/actions/ActionsCopy.tsx
  packages/x/components/actions/ActionsFeedback.tsx
  packages/x/components/actions/ActionsMenu.tsx
  packages/x/components/actions/__tests__/audio.test.tsx
  packages/x/components/actions/__tests__/copy.test.tsx
  packages/x/components/actions/__tests__/feedback.test.tsx
  packages/x/components/actions/__tests__/index.test.tsx
  packages/x/components/actions/demo/_semantic.tsx
  packages/x/components/actions/demo/basic.tsx
  packages/x/components/actions/demo/sub.tsx
  packages/x/components/actions/demo/variant.tsx
  packages/x/components/actions/index.tsx
  packages/x/components/actions/style/audio.tsx
  packages/x/components/actions/style/copy.ts
  packages/x/components/actions/style/feedback.ts
  packages/x/components/actions/style/index.ts
  packages/x/components/bubble/Bubble.tsx
  packages/x/components/index.ts
  packages/x/components/locale/index.tsx
  packages/x/components/locale/useLocale.ts
  packages/x/components/locale/zh_CN.ts
  packages/x/components/sender/index.tsx
  packages/x/components/x-provider/demo/locale.tsx
  packages/x/docs/playground/agent-tbox.en-US.md
  packages/x/docs/playground/agent-tbox.tsx
  packages/x/docs/playground/agent-tbox.zh-CN.md
  packages/x/docs/playground/copilot.en-US.md
  packages/x/docs/playground/copilot.tsx
  packages/x/docs/playground/copilot.zh-CN.md
  packages/x/docs/playground/independent.en-US.md
  packages/x/docs/playground/independent.tsx
  packages/x/docs/playground/independent.zh-CN.md
  packages/x/docs/x-sdk/demos/x-chat/model.tsx
  packages/x/docs/x-sdk/demos/x-conversations/multi-instances.tsx
  packages/x/docs/x-sdk/demos/x-conversations/operations.tsx
  packages/x/docs/x-sdk/demos/x-request/model.tsx
  packages/x/docs/x-sdk/use-x-chat.zh-CN.md
Labels: javascript, lgtm

#1142 chore: add MIT LICENSE for x-*** and add test:dekko of main workflow
  .github/workflows/main.yml
  packages/x-markdown/BUG_VERSIONS.json
  packages/x-markdown/LICENSE
  packages/x-sdk/BUG_VERSIONS.json
  packages/x-sdk/LICENSE
  packages/x/README.md
Labels: documentation, lgtm

#1143 fix: ThoughtChain.Item style fix
  packages/x/components/thought-chain/Item.tsx
  packages/x/components/thought-chain/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/thought-chain/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/thought-chain/style/item.ts
  packages/x/components/x-provider/__tests__/__snapshots__/index.test.tsx.snap
  packages/x/tests/__snapshots__/changelog.test.ts.snap
Labels: bug, lgtm
