Repository ant-design/x, pull requests merged in 2025-07, with the labels that each got.

#974 chore: update deps and cleanup package.json files
  biome.json
  package.json
  packages/x-card/package.json
  packages/x-markdown/package.json
  packages/x-sdk/package.json
  packages/x/.dumi/theme/builtins/Antd.tsx
  packages/x/.dumi/theme/builtins/ComponentMeta/index.tsx
  packages/x/.dumi/theme/builtins/Previewer/CodePreviewer.tsx
  packages/x/components/think/Think.tsx
  packages/x/components/use-x-agent/demo/model.tsx
  packages/x/components/x-request/index.ts
  packages/x/package.json
  packages/x/scripts/generate-authors.ts
Labels: dependencies

#986 feat: feat_x_markdown
  .gitignore
  biome.json
  package.json
  packages/x-markdown/.fatherrc.ts
  packages/x-markdown/package.json
  packages/x-markdown/plugins/Latex/index.js
  packages/x-markdown/src/XMarkdown/__test__/Parser.test.tsx
  packages/x-markdown/src/XMarkdown/__test__/hooks.test.tsx
  packages/x-markdown/src/XMarkdown/__test__/index.test.tsx
  packages/x-markdown/src/XMarkdown/core/Config.ts
  packages/x-markdown/src/XMarkdown/core/Lexer.ts
  packages/x-markdown/src/XMarkdown/core/Parser.ts
  packages/x-markdown/src/XMarkdown/core/Renderer.ts
  packages/x-markdown/src/XMarkdown/core/index.ts
  packages/x-markdown/src/XMarkdown/hooks/useStreaming.ts
  packages/x-markdown/src/XMarkdown/index.tsx
  packages/x-markdown/src/XMarkdown/interface.ts
  packages/x-markdown/src/index.ts
  packages/x-markdown/src/plugins/HighlightCode/__test__/index.test.tsx
  packages/x-markdown/src/plugins/HighlightCode/index.tsx
  packages/x-markdown/src/plugins/Latex/__test__/__snapshots__/index.test.tsx.snap
  packages/x-markdown/src/plugins/Latex/__test__/index.test.tsx
  packages/x-markdown/src/plugins/Latex/index.ts
  packages/x/.dumi/theme/common/ThemeSwitch/index.tsx
  packages/x/.dumirc.ts
  packages/x/components/index.ts
  packages/x/components/notification/demo/hooks.tsx
  packages/x/components/notification/index.tsx
  packages/x/docs/x-markdown/demo/basic.md
  packages/x/docs/x-markdown/demo/basic.tsx
  packages/x/docs/x-markdown/demo/components.md
  packages/x/docs/x-markdown/demo/components.tsx
  packages/x/docs/x-markdown/demo/index.css
  packages/x/docs/x-markdown/demo/plugin.css
  packages/x/docs/x-markdown/demo/plugin.md
  packages/x/docs/x-markdown/demo/plugin.tsx
  packages/x/docs/x-markdown/demo/streaming.md
  packages/x/docs/x-markdown/demo/streaming.tsx
  packages/x/docs/x-markdown/demo/supersets.md
  packages/x/docs/x-markdown/demo/supersets.tsx
  packages/x/docs/x-markdown/introduce.en-US.md
  packages/x/docs/x-markdown/introduce.zh-CN.md
  packages/x/package.json
  packages/x/scripts/generate-authors.ts
  packages/x/tsconfig.json
Labels: documentation, enhancement

#992 chore: use correct minimatch types
  package.json
Labels: documentation, lgtm

#996 docs: supplementary documents of notification
  packages/x/.dumi/theme/common/ThemeSwitch/index.tsx
  packages/x/components/conversations/style/index.ts
  packages/x/components/notification/index.en-US.md
  packages/x/components/notification/index.zh-CN.md
  packages/x/scripts/generate-authors.ts
Labels: documentation, lgtm

#1001 docs: utoo usage
  README-zh_CN.md
  README.md
Labels: documentation, lgtm

#962 feat: add slot mode for sender
  biome.json
  package.json
  packages/x/.dumi/theme/slots/Header/Actions.tsx
  packages/x/components/_util/hooks/use-get-state.ts
  packages/x/components/conversations/__tests__/index.test.tsx
  packages/x/components/conversations/demo/basic.tsx
  packages/x/components/conversations/demo/shortcutKeys.tsx
  packages/x/components/conversations/hooks/useGroupable.ts
  packages/x/components/conversations/index.tsx
  packages/x/components/index.ts
  packages/x/components/locale/index.tsx
  packages/x/components/notification/demo/hooks.tsx
  packages/x/components/notification/index.tsx
  packages/x/components/sender/SlotTextArea.tsx
  packages/x/components/sender/TextArea.tsx
  packages/x/components/sender/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/sender/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/sender/__tests__/index.test.tsx
  packages/x/components/sender/__tests__/slot.test.tsx
  packages/x/components/sender/context.ts
  packages/x/components/sender/demo/slot-filling.md
  packages/x/components/sender/demo/slot-filling.tsx
  packages/x/components/sender/index.en-US.md
  packages/x/components/sender/index.tsx
  packages/x/components/sender/index.zh-CN.md
  packages/x/components/sender/interface.ts
  packages/x/components/sender/style/index.ts
  packages/x/components/sender/style/slot-textarea.ts
  packages/x/components/think/demo/status.tsx
  packages/x/components/x-provider/__tests__/index.test.tsx
  packages/x/components/x-provider/context.ts
  packages/x/components/x-provider/demo/locale.tsx
  packages/x/components/x-provider/demo/theme.tsx
  packages/x/components/x-provider/index.tsx
  packages/x/package.json
Labels: enhancement, 2.x, lgtm

#1017 fixed: semantic of filelist
  components/attachments/FileList/index.tsx
  components/attachments/demo/_semantic.tsx
  components/attachments/index.tsx
  components/attachments/style/fileCard.ts
Labels: bug, lgtm

#1036 chore: fix dumi useLocale type error
  .dumi/hooks/useLocale.ts
Labels: bug, lgtm

#1054 fix: lint error
  components/actions/interface.ts
Labels: lgtm

#1081 feat: add ref of components 2.0
  packages/x/components/actions/ActionsFeedback.tsx
  packages/x/components/actions/ActionsMenu.tsx
  packages/x/components/actions/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/actions/__tests__/index.test.tsx
  packages/x/components/actions/index.tsx
  packages/x/components/conversations/__tests__/index.test.tsx
  packages/x/components/conversations/index.tsx
  packages/x/components/sender/SenderHeader.tsx
  packages/x/components/sender/TextArea.tsx
  packages/x/components/sender/__tests__/index.test.tsx
  packages/x/components/sender/index.tsx
  packages/x/components/think/Think.tsx
  packages/x/components/think/__tests__/index.test.tsx
  packages/x/components/thought-chain/Item.tsx
  packages/x/components/thought-chain/__tests__/index.test.tsx
  packages/x/components/thought-chain/__tests__/item.test.tsx
  packages/x/components/thought-chain/index.tsx
Labels: enhancement, javascript, lgtm
