Repository ant-design/x, pull requests merged in 2025-06, with the labels that each got.

#909 chore: fix pre-commit not effective
  biome.json
  package.json
Labels: documentation, lgtm

#898 fix: ConversationsItem title display [Object Object] and support extr…
  components/conversations/Item.tsx
  components/conversations/__tests__/__snapshots__/index.test.tsx.snap
  components/conversations/index.tsx
  components/conversations/interface.ts
Labels: bug, lgtm

#905 feat: add x-provider shortcut key configuration and universal capabilities
  package.json
  packages/x/components/_util/hooks/use-shortcut-keys.ts
  packages/x/components/_util/hooks/use-x-component-config.ts
  packages/x/components/_util/type.ts
  packages/x/components/conversations/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/conversations/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/conversations/__tests__/index.test.tsx
  packages/x/components/conversations/demo/shortcutKeys.md
  packages/x/components/conversations/demo/shortcutKeys.tsx
  packages/x/components/conversations/index.en-US.md
  packages/x/components/conversations/index.tsx
  packages/x/components/conversations/index.zh-CN.md
  packages/x/components/x-provider/context.ts
  packages/x/components/x-provider/demo/direction.md
  packages/x/components/x-provider/demo/direction.tsx
  packages/x/components/x-provider/demo/shortcutKeys.md
  packages/x/components/x-provider/demo/shortcutKeys.tsx
  packages/x/components/x-provider/demo/theme.md
  packages/x/components/x-provider/demo/theme.tsx
  packages/x/components/x-provider/demo/use.md
  packages/x/components/x-provider/index.en-US.md
  packages/x/components/x-provider/index.tsx
  packages/x/components/x-provider/index.zh-CN.md
  packages/x/package.json
Labels: bug, enhancement, lgtm

#914 chore: sync main to next branch
  .github/workflows/preview-deploy.yml
  packages/x/components/conversations/Item.tsx
  packages/x/components/conversations/__tests__/__snapshots__/index.test.tsx.snap
  packages/x/components/conversations/index.tsx
  packages/x/components/conversations/interface.ts
Labels: BranchAutoMerge

#918 chore: add antd token docs
  .github/workflows/preview-deploy.yml
  packages/x/.dumi/theme/builtins/ComponentTokenTable/index.tsx
  packages/x/components/theme/components.ts
  packages/x/components/theme/genStyleUtils.ts
  packages/x/components/theme/interface/alias.ts
  packages/x/components/theme/interface/components.ts
  packages/x/components/theme/interface/cssinjs-utils.ts
  packages/x/components/theme/interface/index.ts
  packages/x/components/theme/interface/maps/colors.ts
  packages/x/components/theme/interface/maps/font.ts
  packages/x/components/theme/interface/maps/index.ts
  packages/x/components/theme/interface/maps/size.ts
  packages/x/components/theme/interface/maps/style.ts
  packages/x/components/theme/interface/presetColors.ts
  packages/x/components/theme/interface/seeds.ts
  packages/x/scripts/generate-token-meta.ts
Labels: documentation, lgtm

#940 docs: enhance theme switching functionality
  .dumi/theme/common/ThemeSwitch/index.tsx
Labels: documentation

#957 fix: motion of collapse
  packages/x/components/conversations/style/index.ts
Labels: bug, lgtm

#946 feat: add think component
  packages/x/components/index.ts
  packages/x/components/theme/interface/components.ts
  packages/x/components/think/Think.tsx
  packages/x/components/think/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/think/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/think/__tests__/__snapshots__/index.test.tsx.snap
  packages/x/components/think/__tests__/demo-extend.test.ts
  packages/x/components/think/__tests__/demo.test.ts
  packages/x/components/think/__tests__/image.test.ts
  packages/x/components/think/__tests__/index.test.tsx
  packages/x/components/think/demo/basic.md
  packages/x/components/think/demo/basic.tsx
  packages/x/components/think/demo/expand.md
  packages/x/components/think/demo/expand.tsx
  packages/x/components/think/demo/status.md
  packages/x/components/think/demo/status.tsx
  packages/x/components/think/icons/think.tsx
  packages/x/components/think/index.en-US.md
  packages/x/components/think/index.tsx
  packages/x/components/think/index.zh-CN.md
  packages/x/components/think/style/index.ts
  packages/x/components/x-provider/context.ts
  packages/x/tests/__snapshots__/index.test.ts.snap
Labels: enhancement, lgtm

#952 feat: add LocaleProvider for X
  .gitignore
  packages/x/.fatherrc.ts
  packages/x/components/locale/en_US.ts
  packages/x/components/locale/index.tsx
  packages/x/components/locale/zh_CN.ts
  packages/x/components/x-provider/__tests__/index.test.tsx
  packages/x/components/x-provider/context.ts
  packages/x/components/x-provider/demo/locale.md
  packages/x/components/x-provider/demo/locale.tsx
  packages/x/components/x-provider/demo/shortcutKeys.tsx
  packages/x/components/x-provider/demo/theme.tsx
  packages/x/components/x-provider/index.en-US.md
  packages/x/components/x-provider/index.tsx
  packages/x/components/x-provider/index.zh-CN.md
Labels: documentation, enhancement, lgtm

#955 fix: conversations disable
  packages/x/components/conversations/__tests__/__snapshots__/demo-extend.test.ts.snap
  packages/x/components/conversations/__tests__/__snapshots__/demo.test.ts.snap
  packages/x/components/conversations/__tests__/index.test.tsx
  packages/x/components/conversations/demo/basic.tsx
  packages/x/components/conversations/demo/shortcutKeys.tsx
  packages/x/components/conversations/hooks/useCreation.tsx
  packages/x/components/conversations/hooks/useGroupable.ts
  packages/x/components/conversations/index.tsx
  packages/x/components/conversations/style/index.ts
Labels: bug, lgtm

#967 chore: fix of fatherrc.ts and package.json
  package.json
  packages/x-card/.fatherrc.ts
  packages/x-card/package.json
  packages/x-markdown/.fatherrc.ts
  packages/x-sdk/.fatherrc.ts
  packages/x-sdk/package.json
Labels: documentation, lgtm
